kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: yelb
  name: burn-cpu-yelb-ui
spec:
  selector:
    namespaces:
      - yelb
    labelSelectors:
      app: yelb-ui
  mode: one
  stressors:
    cpu:
      workers: 2
      load: 100
  duration: 30m
