apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: burn-cpu-yelb-ui-schedule
spec:
  schedule: '*/30 {{CURRENT_HOUR_PLUS_ONE}} * * {{CURRENT_DAY_OF_WEEK}}'
  historyLimit: 2
  concurrencyPolicy: 'Allow'
  type: 'StressChaos'
  stressChaos:
    mode: all
    selector:
      namespaces:
        - yelb
      labelSelectors:
        app: yelb-ui
    stressors:
      cpu:
        workers: 2
        load: 100
        options: ["--cpu 2", "--hdd 1"]
    duration: 30m
